name: myoconverter
channels:
  - conda-forge
  - opensim-org
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h682ed8b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py310haaa1140_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310hf5b66c1_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h248ca61_0
  - contourpy=1.2.1=py310h21239e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - double-conversion=3.3.1=h286801f_0
  - eigen=3.4.0=h49c215f_1
  - etils=1.12.2=pyhd8ed1ab_0
  - expat=2.7.3=haf25636_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - fmt=11.2.0=h440487c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py310hf4fd40f_0
  - fpdf=1.7.2=pyhd8ed1ab_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - frozenlist=1.7.0=py310ha18c8e3_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - glfw=3.4=hc919400_1
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=haf38c7b_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_he65715a_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsoncpp=1.9.6=h726d253_1
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libass=0.17.4=hcbd7ca7_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libboost=1.88.0=h18cd856_6
  - libboost-devel=1.88.0=hf450f58_6
  - libboost-headers=1.88.0=hce30654_6
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=20_osxarm64_openblas
  - libccd-double=2.1=h9a09cb3_2
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libclang13=21.1.6=default_h6e8f826_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.6=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.2=he69a767_0
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.6=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmujoco=3.3.5=h2f9c0ae_0
  - libnetcdf=4.9.3=nompi_h80c4520_103
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.1=h944245b_1
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.60.0=h5c55ec3_0
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.7.1=h4030677_1
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libxslt=1.1.43=hb2570ba_1
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - lodepng=20220109=hf86a087_0
  - loguru=0.7.3=pyh707e725_0
  - lxml=6.0.2=py310hca4a255_2
  - lz4-c=1.10.0=h286801f_1
  - matplotlib=3.8.4=py310hb6292c7_2
  - matplotlib-base=3.8.4=py310hedb7998_2
  - msgpack-python=1.1.2=py310h0e897d2_1
  - mujoco=3.3.5=hddcfdd1_0
  - mujoco-python=3.3.5=np2py310h00e8d6d_0
  - mujoco-samples=3.3.5=h082659d_0
  - mujoco-simulate=3.3.5=h082659d_0
  - multidict=6.6.3=py310hdf261b0_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.2=pyhd8ed1ab_0
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=1.21.6=py310h2e04ed8_0
  - openblas=0.3.25=openmp_h55c453e_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - opensim=4.4.1=py310np121
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py310h1cdf563_1
  - pango=1.56.4=h875632e_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pillow=12.0.0=py310hab9784f_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.0=hf83150c_0
  - propcache=0.3.1=py310hc74094e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - pybind11-abi=11=hc364b38_1
  - pycparser=2.22=pyh29332c3_1
  - pyglfw=2.10.0=pyha770c72_0
  - pyopengl=3.1.10=pyh534df25_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyvista=0.46.4=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.9.3=hb266e41_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py310h48c93d9_0
  - scipy=1.11.2=py310h0975f3d_0
  - scooby=0.11.0=pyhd8ed1ab_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - spirv-tools=2025.4=ha7d2532_0
  - sqlite=3.51.0=h81ab1b7_0
  - statsmodels=0.14.2=py310hb3e58dc_0
  - svt-av1=3.1.2=h12ba402_0
  - tbb=2022.3.0=h66ce52b_1
  - tbb-devel=2022.3.0=h41f9aa9_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinyxml2=11.0.0=ha1acc90_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py310hfe3a0ae_2
  - trimesh=4.8.3=pyh7b2049a_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utfcpp=4.0.8=hce30654_0
  - vtk=9.5.2=hd81e049_0
  - vtk-base=9.5.2=py310h56b1365_0
  - vtk-io-ffmpeg=9.5.2=h1a781ad_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yarl=1.22.0=py310hf4fd40f_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py310hf151d32_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - contourpy==1.3.2
    - cycler==0.12.1
    - defusedxml==0.7.1
    - fonttools==4.60.1
    - fpdf2==2.7.5
    - idna==3.11
    - kiwisolver==1.4.9
    - loguru==0.7.0
    - matplotlib==3.10.7
    - mujoco==2.3.7
    - numpy==1.26.4
    - packaging==25.0
    - pillow==12.0.0
    - platformdirs==4.5.0
    - pooch==1.8.2
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pyvista==0.39.1
    - requests==2.32.5
    - scooby==0.11.0
    - six==1.17.0
    - typing_extensions==4.15.0
    - urllib3==2.5.0
    - vtk==9.2.6

prefix: "/Users/careycai/micromamba/envs/myoconverter"
